### ISSUE TITLE
[Errata]: Can confirm still no support for physical Sense Hat V2 in Scratch 3

### ISSUE THREAD

**Issue by Rueful-Pi** [raspberrypipress/official-raspberry-pi-beginners-guide-5e#4]
### What format of the book has this error? You may select more than one option.

Print

### What language of the book has this error?

English (EN)

### Page Number or Section

Pg. 155 Physical computing with the Sense Hat

### Detailed description

5th edition of The Official Raspberry Pi Beginner's Guide(Chap 7) Raspberry Pi 5 + Physical Sense Hat V2, Scratch 3 lessons are not possible to complete, as of Feb. 23, 2024. I am running 64 bit Pi OS debian. I have not tried the emulator.

**Comment by bjepson** [comment]
Hi, @Rueful-Pi, thanks for reporting the issue. Could you have a look at these two issues and let us know if one of them applies to your situation?

https://github.com/raspberrypi/bookworm-feedback/issues/91

https://github.com/raspberrypi/bookworm-feedback/issues/148

Note that 148 mentions that work is being done on the Sense HAT issues. 

Best,

Brian

**Comment by Rueful-Pi** [comment]
Thanks for your reply  @bjepson.

Yes, issue seems to apply to what I experience. I am using Scratch 3.30.8. Seemed to work fine to turn on/off LEDs, utilising push-button, and sounding active buzzer. I was able to complete the rather enjoyable traffic light project.

 #https://github.com/raspberrypi/bookworm-feedback/issues/91#issuecomment-1768608844
I would try this solution. But, I haven't the slightest clue which config.txt(an awful lot of those lurking around) and where said text file could be found, in order to try "kernel=kernel8.img". I don't know if I have "16KB pages" or even what that relly is reffering to.
Sorry, I just started dipping my toes into Raspberry pi, Physical computing, coding and Linux, 2 weeks ago when I got a hold of the book and the Pi. I am that demographic the book is aimed at... Beginner.

**Comment by bjepson** [comment]
You're welcome @Rueful-Pi. Based on what you're saying, I think that issue 91 might not apply to you (the one with all the config changes). It sounds like Scratch is working, but the Sense HAT is only partially working? If so, then I think that the comment posted to issue 148 might be relevant to you, and you may want to sign up for a GitHub account and subscribe to that issue so you can get notifications.

You may also want to try flashing an SD card with the 32-bit version of Raspberry Pi OS (I'm not certain whether or how well it works with the 5 though). I have gotten better results with the Sense HAT emulator, a Raspberry Pi 4, and a 32-bit OS while I wait for the overall Sense HAT issues to be resolved. But I am not certain it will fix issues with the real Sense HAT, so it may be best to follow that issue and await a fix because it sounds like it is coming soon.

Best,

Brian

**Comment by bjepson** [comment]
Sorry @Rueful-Pi  -- I'm not sure why I suggested in my previous comment that you get a GitHub account when you clearly have one 🙂

**Comment by Rueful-Pi** [comment]
Thanks @bjepson. I will subscribe, as you suggested. Yes, Scratch 3 is working on the Pi 5 generally, just doesn't interact at all with the physical Sense HAT. Although, Thonny works well with the physical HAT so I am working through those lessons in python code.

**Comment by grega** [comment]
The next release of Scratch Desktop fixes this issue (along with a handful of other physical and emulator Sense HAT bugs), expect an updated package soon (within a week or two)...

**Comment by Rueful-Pi** [comment]
Thank you @grega. I appreciate the update, really cool.

**Comment by grega** [comment]
We published an updated version of Scratch Desktop (3.30.9) on April 11th: https://archive.raspberrypi.org/debian/pool/main/s/scratch3/?C=M;O=D

This should fix the issues mentioned here.

There's also a new version of the Sense Hat emulator (1.2.2), released on the same day, which fixes some issues relating to incorrect sensor readings when interacting with the emulator using Scratch Desktop: https://archive.raspberrypi.org/debian/pool/main/s/sense-emu/?C=M;O=D

**Comment by Rueful-Pi** [comment]
Thanks @grega I did use the Physical Sense Hat the other day and it all worked perfectly with Scratch. I hadn't tried the Emulator though.
